### ISSUE TITLE
missing OAINumber from cpp-qt5-client

### ISSUE THREAD

**Issue by yandreiy** [deribit/deribit-api-clients#1] opened 2019-05-28 13:07 UTC
Did a quick test to compile the cpp-qt5 client and it fails with:

```
/cpp-qt5-client/client/OAIBook_summary.h:25:` error: OAINumber.h: No such file or directory
 #include "OAINumber.h"
          ^~~~~~~~~~~~~

```

**Comment by lacksfish** [comment] 2019-05-29 10:26
Good spot, thanks for notifying!

Unfortunately, even though this header file is required, it does not seem to get appropriately generated by openAPI. Is there a possibility for you to use `cpp-restsdk` instead of the qt5 client? We will investigate the current issue you report and will update our findings soon.

**Comment by lacksfish** [comment] 2019-05-31 08:50
After further investigation, I am certain that this bug exists in the `cpp-qt5-client` since the olden days of swagger (as it exists on other, older projects that use this generator) and mightn't be fixed soon. I promise I'll keep an eye out and have opened an upstream bugreport [here](https://github.com/OpenAPITools/openapi-generator/issues/3037), but I wouldn't get my hopes up.

Pull request https://github.com/deribit/deribit-api-clients/pull/5 removes the `cpp-qt5-client` for now, please excuse the inconvenience. Closing this.

**Comment by macjohnny** [comment] 2019-06-03 06:20
@lacksfish the issue is fixed (see https://github.com/OpenAPITools/openapi-generator/issues/3037), so with the next release of OpenAPI Generator you could add the `cpp-qt5-client` again, if you want to.

**Comment by lacksfish** [comment] 2019-06-03 09:07
Seems to be scheduled to release 4.0.2 around 15th of June, but perhaps we can have it before that day as it is merged to `master` already. Will give it a spin

**Comment by lacksfish** [comment] 2019-06-03 12:21
Should be resolved on latest `master`. Closing this for now.

**Closed by lacksfish** 2019-06-03 12:21 UTC
Labels: bug
